org: josmelnyh89
app: challenge-rimac-lambda-rest-api-app
service: challenge-rimac-lambda-rest-api

plugins:
  - serverless-dynamodb-local
  - serverless-offline
  - serverless-mocha-plugin

custom:
  tableName: "vehiculos-${self:provider.stage}"
  serverless-mocha-plugin:
    preTestCommands:
      - bash startOffline.sh
    postTestCommands:
      - bash stopOffline.sh

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - { "Fn::GetAtt": ["VehiculosDynamoDBTable", "Arn"] }
  environment:
    VEHICULOS_TABLE: ${self:custom.tableName}
    SLS_DEBUG: "*"

functions:
  vehiculo-app:
    handler: index.handler
    events:
      - http: ANY /
      - http: "ANY {proxy+}"

resources:
  Resources:
    VehiculosDynamoDBTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        AttributeDefinitions:
          - AttributeName: vehiculoId
            AttributeType: S
        KeySchema:
          - AttributeName: vehiculoId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.tableName}
